export const sample_foods = [
    {
        id: '1',
        name: 'biryani',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        origins: ['india'],
        stars: 4.5,
        imageUrl: 'food-1.jpeg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '2',
        name: 'chicken biryani',
        price: 20,
        cookTime: '20-30',
        favorite: true,
        origins: ['persia', 'middle east', 'china'],
        stars: 5,
        imageUrl: 'food-2.jpg',
        tags: ['SlowFood', 'Lunch'],
    },
    {
        id: '3',
        name: 'fish-biryani',
        price: 5,
        cookTime: '10-15',
        favorite: false,
        origins: ['germany', 'us'],
        stars: 3.5,
        imageUrl: 'food-3.jpg',
        tags: ['FastFood', 'Hamburger'],
    },
    {
        id: '4',
        name: 'masala-dosa',
        price: 2,
        cookTime: '15-20',
        favorite: true,
        origins: ['belgium', 'france'],
        stars: 3,
        imageUrl: 'food-4.jpeg',
        tags: ['FastFood', 'Fry'],
    },
    {
        id: '5',
        name: 'mutton-biryani',
        price: 11,
        cookTime: '40-50',
        favorite: false,
        origins: ['india', 'asia'],
        stars: 3.5,
        imageUrl: 'food-5.webp',
        tags: ['SlowFood', 'Soup'],
    },
    {
        id: '6',
        name: 'south indian',
        price: 9,
        cookTime: '40-50',
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'food-6.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
];

export const sample_tags = [
    { name: 'All', count: 6 },
    { name: 'indian food', count: 4 },
    { name: 'biryani', count: 2 },
    { name: 'Lunch', count: 3 },
    { name: 'south indian', count: 2 },
    { name: 'masala-dosa', count: 1 },
    { name: 'fishbiryani', count: 1 },
    { name: 'mutton biryani', count: 1 },
];

export const sample_users = [
    {
        id: 1,
        name: 'praba',
        email: 'praba@gmail.com',
        password: '12345',
        address: 'attur salem',
        isAdmin: false,
    },
    {
        id: 2,
        name: 'priya',
        email: 'priya@gmail.com',
        password: '12345',
        address: 'salem',
        isAdmin: true,
    },
];
